### ISSUE TITLE
For multi devices: www-data in "lp" group

### ISSUE THREAD

**Issue by honigabor** [sbs20/scanserv#13]
Hi!
First of all, many thanks for this great frontend especially usable for small systems like ARMv61.
I have found that my www-data user can not access scanner device causing scanserv fails to get device and setup.
As multi devices (printer/scanner) such as Samsung CLX3180 series /dev/bus/usb/... belong to "lp" group, it's necessary to add www-data to "lp" with `sudo usermod -a -G lp www-data`.
Afterwards You can check with `sudo su -m www-data -c 'scanimage -L'` and device appears near the top.
Bests,
Hong

**Comment by sbs20** [comment]
My pleasure! I'm glad it's still useful for you. I have updated the docs a bit which will hopefully help.
